### ISSUE TITLE
Is Resnet V2?

### ISSUE THREAD

**Issue by TccccD** [diux-dev/imagenet18#10]
Is Resnet V2? @yaroslavvb @bearpelican

**Comment by yaroslavvb** [comment]
What is the definition of Resnet V2?

The model used is a slight modification version of TorchVision resnet (https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py) with final pooling layer modified to accept variable size receptive field (it pools arbitrary input spatial size into 1x1 spatial), here's the model [definition](https://github.com/diux-dev/imagenet18/blob/master/training/resnet.py)
