### ISSUE TITLE
Spot Instance or On-Demand instances

### ISSUE THREAD

**Issue by chrishkchris** [diux-dev/imagenet18#24]
Recently I was asked by my supervisor to try to run the code, but I need to know more about the actual cost of running the code. 

I saw the code utilize ncluster and awscli for cloud management. 

Does the code utilize spot instances or on-demand p3.16xlarge instances of AWS? 

In other words:
A single run cost around $40 with spot instances (ref: https://www.fast.ai/2018/08/10/fastai-diu-imagenet/)
or
It costs $118.07 ? (ref: https://dawn.cs.stanford.edu/benchmark/ImageNet/train.html)

Does the code terminate the p3.16xlarge instances automatically upon any termination condition? Or I need to terminate the p3.16xlarge instances by hand after around 18 minutes?

Thanks a lot!

**Comment by yaroslavvb** [comment]
You need to terminate by hand. There's a flag "--spot" to use spot instances

**Comment by chrishkchris** [comment]
Thanks for the answer. I've tried the code, it is really great!
